=== hykiukira/astra-client/src/main/java/srcastra/template2.dtd
<!-- DTD for JClass PageLayout Templates -->
<!ELEMENT JCPAGETEMPLATE (PAGE+)>
<!ATTLIST JCPAGETEMPLATE TITLE CDATA #IMPLIED>
<!ELEMENT PAGE (LOCATION,SIZE,FRAME+,FLOWFRAME*,FLOWPAGE,FLOWSECTION)>
<!ATTLIST PAGE NAME CDATA #REQUIRED
UNIT (inches|points|cm|cms|centimeters|centimetres) "inches"
COLOR CDATA #IMPLIED
ORIENTATION (automatic|portrait|landscape) "automatic"
FIRST (True|true|TRUE|False|false|FALSE) "false">
<!ELEMENT FRAME (LOCATION,SIZE,BORDER?,COLUMN?,MARGIN?)>
<!ATTLIST FRAME NAME CDATA #REQUIRED
UNIT (inches|points|cm|cms|centimeters|centimetres) "inches"
COLOR CDATA #IMPLIED>
<!ELEMENT LOCATION EMPTY>
<!ATTLIST LOCATION X CDATA #REQUIRED
Y CDATA #REQUIRED>
<!ELEMENT SIZE EMPTY>
<!ATTLIST SIZE WIDTH CDATA #REQUIRED
HEIGHT CDATA #REQUIRED>
<!ELEMENT BORDER EMPTY>
<!ATTLIST BORDER TYPE
(blank|broken|dashed|double|none|plain|regular|single) "blank"
COLOR CDATA "black"
THICKNESS CDATA #IMPLIED>
<!ELEMENT COLUMN EMPTY>
<!ATTLIST COLUMN COUNT CDATA #REQUIRED
SPACING CDATA #IMPLIED>
<!ELEMENT MARGIN EMPTY>
<!ATTLIST MARGIN TOP CDATA #REQUIRED
RIGHT CDATA #REQUIRED
LEFT CDATA #REQUIRED
BOTTOM CDATA #REQUIRED>
<!ELEMENT FLOWFRAME EMPTY>
<!ATTLIST FLOWFRAME NAME CDATA #REQUIRED>
<!ELEMENT FLOWPAGE EMPTY>
<!ATTLIST FLOWPAGE NAME CDATA #REQUIRED>
<!ELEMENT FLOWSECTION EMPTY>
<!ATTLIST FLOWSECTION NAME CDATA #REQUIRED>

=== hykiukira/astra-client/src/main/java/srcastra/template.xml
<?xml version="1.0"?>

<!DOCTYPE JCPAGETEMPLATE SYSTEM "template2.dtd">

<JCPAGETEMPLATE TITLE="8p5x11">

    <PAGE NAME="8p5x11" UNIT="cms">

        <MARGIN TOP="1" RIGHT="1" LEFT="1" BOTTOM="1"/>

        <LOCATION X="0" Y="0"/>

        <SIZE WIDTH="21" HEIGHT="30"/>

        <FRAME NAME="header" UNIT="cms" COLUMN="2">

            <LOCATION X="1" Y="0.25"/>

            <SIZE WIDTH="19" HEIGHT="8"/>

        </FRAME>

        <FRAME NAME="body" UNIT="cm" COLUMN="1">

            <LOCATION X="1" Y="8"/>

            <SIZE WIDTH="19" HEIGHT="9"/>

            <COLUMN COUNT="2"/>

        </FRAME>

        <FRAME NAME="footer" UNIT="inches" COLOR="grey">

            <LOCATION X="1" Y="10.25"/>

            <SIZE WIDTH="6.5" HEIGHT="0.75"/>

        </FRAME>

        <FLOWFRAME NAME="body"/>

        <FLOWPAGE NAME="8p5x11"/>

        <FLOWSECTION NAME="8p5x11"/>

    </PAGE>

</JCPAGETEMPLATE>
